version: '3'

services:
  db:
    image: 'postgres:11.1-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'squirrel'
    ports:
      - '5432:5432'
    volumes:
      - './.db:/var/lib/postgresql/data'
